import type { Metadata } from 'next'
import '@/app/globals.css'
import { Toaster } from '@/components/ui/toaster'
import { ToastSonner } from '@/components/ui/sonner'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
    title: 'NexaDash',
    description: 'Generated by AppStoneLab',
}
const PlusJakartaSans = Plus_Jakarta_Sans({
    subsets: ['latin'],
})

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang="en"
            className="scroll-smooth"
            dir="ltr"
            suppressHydrationWarning
        >
            <body className={cn('bg-gray-400 text-sm/[22px] font-normal text-gray antialiased dark:bg-black dark:text-gray-500', PlusJakartaSans.className)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster />
                    <ToastSonner />
                </ThemeProvider>
            </body>
        </html>
    )
}
